name: 'Release – Publish to npm'

on:
  push:
    tags:
      - 'v*.*.*' # Matches v1.2.3, v0.0.1, etc.

permissions:
  contents: read # to fetch code from the repo
  id-token: write # to mint the provenance token for npm

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies (clean)
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test --if-present

      - name: Build package
        run: npm run build

      - name: Publish to npm (with provenance)
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
